In [4]:

library(readr)
library(dplyr)
library(sqldf);

In [30]:

invisible({
person <- read_csv(unz("mimic_IV_omop_data_csv.zip", "mimic_IV_omop_data_csv/person.csv"))

condition_occurrence <- read_csv(unz("mimic_IV_omop_data_csv.zip", "mimic_IV_omop_data_csv/condition_occurrence.csv"))

procedure_occurrence <- read_csv(unz("mimic_IV_omop_data_csv.zip", "mimic_IV_omop_data_csv/procedure_occurrence.csv"))

measurement <- read_csv(unz("mimic_IV_omop_data_csv.zip", "mimic_IV_omop_data_csv/measurement.csv"))

visit_occurrence <- read_csv(unz("mimic_IV_omop_data_csv.zip", "mimic_IV_omop_data_csv/visit_occurrence.csv"))

drug_exposure <- read_csv(unz("mimic_IV_omop_data_csv.zip", "mimic_IV_omop_data_csv/drug_exposure.csv"))

observation <- read_csv(unz("mimic_IV_omop_data_csv.zip", "mimic_IV_omop_data_csv/observation.csv"))

concept <- read_csv(unz("mimic_IV_omop_data_csv.zip", "mimic_IV_omop_data_csv/2b_concept.csv"))

concept_relationship <- read_csv(unz("mimic_IV_omop_data_csv.zip", "mimic_IV_omop_data_csv/2b_concept_relationship.csv"))
    })

Rows: 100 Columns: 18
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): gender_source_value, race_source_value, ethnicity_source_value
dbl (9): person_id, gender_concept_id, year_of_birth, race_concept_id, ethni...
lgl (6): month_of_birth, day_of_birth, birth_datetime, location_id, provider...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 16441 Columns: 16
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (1): condition_source_value
dbl  (6): condition_occurrence_id, person_id, condition_concept_id, conditio...
lgl  (5): stop_reason, provider_id, visit_detail_id, condition_status_source...
dttm (2): condition_start_datetime, condition_end_datetime
date (2): condition_start_date, condition_end_date

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 18447 Columns: 14
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (1): procedure_source_value
dbl  (8): procedure_occurrence_id, person_id, procedure_concept_id, procedur...
lgl  (3): provider_id, visit_detail_id, modifier_source_value
dttm (1): procedure_datetime
date (1): procedure_date

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Warning message:
“One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)”
Rows: 338550 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr   (3): measurement_source_value, unit_source_value, value_source_value
dbl  (12): measurement_id, person_id, measurement_concept_id, measurement_ty...
lgl   (3): measurement_time, operator_concept_id, provider_id
dttm  (1): measurement_datetime
date  (1): measurement_date

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 852 Columns: 17
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (3): visit_source_value, admitting_source_value, discharge_to_source_value
dbl  (8): visit_occurrence_id, person_id, visit_concept_id, visit_type_conce...
lgl  (2): provider_id, care_site_id
dttm (2): visit_start_datetime, visit_end_datetime
date (2): visit_start_date, visit_end_date

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 18229 Columns: 23
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (3): drug_source_value, route_source_value, dose_unit_source_value
dbl  (8): drug_exposure_id, person_id, drug_concept_id, drug_type_concept_id...
lgl  (8): verbatim_end_date, stop_reason, refills, days_supply, sig, lot_num...
dttm (2): drug_exposure_start_datetime, drug_exposure_end_datetime
date (2): drug_exposure_start_date, drug_exposure_end_date

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 31390 Columns: 18
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (2): value_as_string, observation_source_value
dbl  (8): observation_id, person_id, observation_concept_id, observation_typ...
lgl  (6): qualifier_concept_id, unit_concept_id, provider_id, visit_detail_i...
dttm (1): observation_datetime
date (1): observation_date

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 3885 Columns: 10
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (6): concept_name, domain_id, vocabulary_id, concept_class_id, standard...
dbl  (1): concept_id
lgl  (1): invalid_reason
date (2): valid_start_DATE, valid_end_DATE

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7716 Columns: 6
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (1): relationship_id
dbl  (2): concept_id_1, concept_id_2
lgl  (1): invalid_reason
date (2): valid_start_DATE, valid_end_DATE

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [18]:

head(person)

  person_id     gender_concept_id year_of_birth month_of_birth day_of_birth
1  3.589913e+18 8507              2095          NA             NA
2 -3.210374e+18 8507              2079          NA             NA
3 -7.755176e+17 8507              2149          NA             NA
4 -2.575767e+18 8507              2050          NA             NA
5 -8.970844e+18 8507              2114          NA             NA
6  4.668337e+18 8507              2073          NA             NA
  birth_datetime race_concept_id ethnicity_concept_id location_id provider_id
1 NA                0            38003563             NA          NA
2 NA                0            38003563             NA          NA
3 NA             8516                   0             NA          NA
4 NA             8516                   0             NA          NA
5 NA             8527                   0             NA          NA
6 NA             8527                   0             NA          NA
  care_site_id person_source_value gender_source_value gender_source_concept_id
1 NA           10009628            M                   0
2 NA           10011398            M                   0
3 NA           10004235            M                   0
4 NA           10024043            M                   0
5 NA           10038933            M                   0
6 NA           10021487            M                   0
  race_source_value      race_source_concept_id ethnicity_source_value
1 NA                              0             HISPANIC/LATINO
2 NA                              0             HISPANIC/LATINO
3 BLACK/AFRICAN AMERICAN 2000001406             NA
4 BLACK/AFRICAN AMERICAN 2000001406             NA
5 WHITE                  2000001404             NA
6 WHITE                  2000001404             NA
  ethnicity_source_concept_id
1 2000001408
2 2000001408
3          0
4          0
5          0
6          0

In [19]:

person %>%
select(person_id, gender_concept_id, gender_source_value) %>%
head()

  person_id     gender_concept_id gender_source_value
1  3.589913e+18 8507              M
2 -3.210374e+18 8507              M
3 -7.755176e+17 8507              M
4 -2.575767e+18 8507              M
5 -8.970844e+18 8507              M
6  4.668337e+18 8507              M

In [21]:
condition_occurrence %>%
select(condition_occurrence_id, condition_concept_id, condition_source_value) %>%
head()

  condition_occurrence_id condition_concept_id condition_source_value
1  7.000818e+18             196523             78791
2 -3.514320e+18             436659             2809
3 -6.297447e+18             435515             2761
4  3.131133e+18             436096             33829
5  2.246710e+18             440383             311
6  3.281005e+18           37311319             27652

In [24]:

sqldf("select 
        condition_occurrence_id,
        condition_concept_id,
        condition_source_value,
        concept_name
       from condition_occurrence a LEFT JOIN concept b on a.condition_concept_id = b.concept_id
       limit 10"
)

   condition_occurrence_id condition_concept_id condition_source_value
1   7.000818e+18             196523             78791
2  -3.514320e+18             436659             2809
3  -6.297447e+18             435515             2761
4   3.131133e+18             436096             33829
5   2.246710e+18             440383             311
6   3.281005e+18           37311319             27652
7  -3.356551e+18             373764             34982
8   2.389445e+18             443238             25002
9  -2.365441e+18             197672             78830
10  8.104095e+18             194406             59969
   concept_name
1  NA
2  NA
3  NA
4  NA
5  NA
6  NA
7  NA
8  NA
9  NA
10 NA