In [1]:

library(readr)
library(dplyr)
library(sqldf);

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Loading required package: gsubfn

Loading required package: proto

Warning message:
“no DISPLAY variable so Tk is not available”
Loading required package: RSQLite

In [8]:
##set root working directory

setwd("/home/jovyan")

In [15]:

person = as.data.frame(read.csv("OMOP/person.csv"))

condition_occurrence = as.data.frame(read.csv("OMOP/condition_occurrence.csv"))

visit_occurrence = as.data.frame(read.csv("OMOP/visit_occurrence.csv"))

drug_exposure = as.data.frame(read.csv("OMOP/drug_exposure.csv"))

observations = as.data.frame(read.csv("OMOP/observation.csv"))

procedure_occurrence = as.data.frame(read.csv("OMOP/procedure_occurrence.csv"))

measurement = as.data.frame(read.csv("OMOP/measurement.csv"))

concept = as.data.frame(read.csv("OMOP/concepts.csv"))

In [17]:

person %>%
select(person_id, gender_concept_id, gender_source_value) %>%
head()

  person_id     gender_concept_id gender_source_value
1  3.589913e+18 8507              M
2 -3.210374e+18 8507              M
3 -7.755176e+17 8507              M
4 -2.575767e+18 8507              M
5 -8.970844e+18 8507              M
6  4.668337e+18 8507              M

In [18]:
condition_occurrence %>%
select(condition_occurrence_id, condition_concept_id, condition_source_value) %>%
head()

  condition_occurrence_id condition_concept_id condition_source_value
1  7.000818e+18             196523             78791
2 -3.514320e+18             436659             2809
3 -6.297447e+18             435515             2761
4  3.131133e+18             436096             33829
5  2.246710e+18             440383             311
6  3.281005e+18           37311319             27652

In [19]:

sqldf("select 
        condition_occurrence_id,
        condition_concept_id,
        condition_source_value,
        concept_name
       from condition_occurrence a LEFT JOIN concept b on a.condition_concept_id = b.concept_id
       limit 10"
)

   condition_occurrence_id condition_concept_id condition_source_value
1   7.000818e+18             196523             78791
2  -3.514320e+18             436659             2809
3  -6.297447e+18             435515             2761
4   3.131133e+18             436096             33829
5   2.246710e+18             440383             311
6   3.281005e+18           37311319             27652
7  -3.356551e+18             373764             34982
8   2.389445e+18             443238             25002
9  -2.365441e+18             197672             78830
10  8.104095e+18             194406             59969
   concept_name
1  Diarrhea
2  Iron deficiency anemia
3  Hypo-osmolality and or hyponatremia
4  Chronic pain
5  Depressive disorder
6  Hypovolemia
7  Toxic encephalopathy
8  Diabetic - poor control
9  Urinary incontinence
10 Urinary tract obstruction